export TERM="xterm-256color"

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Path to oh-my-zsh custom folder
ZSH_CUSTOM=$HOME/.oh-my-zsh-custom

ZSH_THEME="powerlevel9k/powerlevel9k"

# Uncomment following line if you want to  shown in the command execution time stamp 
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
HIST_STAMPS="dd.mm.yyyy"

ZSH_DISABLE_COMPFIX="true"

if [[ $(uname) == "Darwin" ]] ; then
    plugins=(git osx history sudo sublime)
else
    plugins=(git history sudo sublime)
fi

# add dotfiles to PATH
export PATH=$PATH:$DOTFILES/bin

# Screen
POWERLEVEL9K_CUSTOM_SCREEN='[[ -n "$STY" ]] && echo -n "\uf26c"'
POWERLEVEL9K_CUSTOM_SCREEN_BACKGROUND="000"
POWERLEVEL9K_CUSTOM_SCREEN_FOREGROUND="blue"

# Theme
POWERLEVEL9K_MODE="nerdfont-complete"

# Dir Length Display
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

# Time
POWERLEVEL9K_TIME_BACKGROUND="000"
POWERLEVEL9K_TIME_FOREGROUND="253"
POWERLEVEL9K_TIME_ICON="\UF43A"
POWERLEVEL9K_TIME_FORMAT="%D{%I:%M %p}"
POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_COLOR="blue"

# VCS
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="black"
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="green"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="black"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="yellow"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="black"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="red"

# USER
POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
POWERLEVEL9K_USER_DEFAULT_FOREGROUND="blue"
POWERLEVEL9K_USER_DEFAULT_BACKGROUND="white"
POWERLEVEL9K_USER_REMOTE_FOREGROUND="black"
POWERLEVEL9K_USER_REMOTE_BACKGROUND="118"
POWERLEVEL9K_USER_SUDO_BACKGROUND="red"
POWERLEVEL9K_USER_SUDO_FOREGROUND="black"
POWERLEVEL9K_USER_REMOTE_SUDO_BACKGROUND="red"
POWERLEVEL9K_USER_REMOTE_SUDO_FOREGROUND="black"
POWERLEVEL9K_USER_TEMPLATE="%n"
POWERLEVEL9K_USER_ICON="\uF415"
POWERLEVEL9K_ROOT_ICON="#"
POWERLEVEL9K_SUDO_ICON="\uF09C"

# IP
POWERLEVEL9K_IP_BACKGROUND="000"
POWERLEVEL9K_IP_FOREGROUND="white"
POWERLEVEL9K_IP_VISUAL_IDENTIFIER_COLOR="blue"

# OS_ICON
POWERLEVEL9K_OS_ICON_BACKGROUND="255"
POWERLEVEL9K_OS_ICON_FOREGROUND="blue"

# Status
POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_STATUS_CROSS=true

# Colors
POWERLEVEL9K_DIR_HOME_FOREGROUND="000"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="000"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="000"

# Prompt
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%f"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}\u2570\uf460%f "
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs user ip virtualenv vcs time)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon ssh dir dir_writable custom_screen root_indicator)

# Theme End

# Source 
source $ZSH/oh-my-zsh.sh